quarkus:
  jooq:
    dialect: POSTGRES
  flyway:
    migrate-at-start: true
  http:
    cors: true
  oidc:
    application-type: web_app
    authentication:
      redirect-path: /auth/callback
      restore-path-after-redirect: true
    token-cache:
      max-size: 1000
      time-to-live: 3M
      clean-up-timer-interval: 1M
    token:
      refresh-expired: true

"%prod":
  quarkus:
    oidc:
      provider: github
      authentication:
        session-age-extension: P30D
    http:
      proxy:
        proxy-address-forwarding: true
        allow-x-forwarded: true
        enable-forwarded-host: true
        enable-forwarded-prefix: true
      header:
        "X-Frame-Options":
          value: "DENY"
        "Strict-Transport-Security":
          value: "max-age=31536000"
        "X-Content-Type-Options":
          value: "nosniff"